plugins {
    id 'java'
    id 'application'
}

group = 'khubanov.ochir'
version = '2.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.8'
    implementation 'javax.activation:activation:1.1.1'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'khubanov.ochir.PeopleNormalizerX2'
}

jar {
    manifest {
        attributes(
                'Main-Class': application.mainClass
        )
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
